# reference: http://www.objc.io/issue-6/travis-ci.html

osx_image: xcode7.1
language: objective-c
before_install: cd Example && pod install && cd -
script:
- xctool test -workspace Example/Example.xcworkspace -scheme URBNDataSource -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
